### ISSUE TITLE
Delete-course

### ISSUE THREAD

**Issue by Sayed94h** [Sayed94h/Restful-API-WebApp#11]
## 5. delete courses

> Assigned to _Sayed kazimi_

**As a user I want to be able to delete a course with a specific course id**

This part is create in a branch called `delete-course` and merged in the `master` when it was completed.

### Task A: HTML

- [x] Added a form with two inputs and one label, one for enter the course id and another for to submit the input
- [x] Added an h2 as a button for Displaying the delete form
- [x] Added a section element for controlling the form position

### Task B: CSS

- [x] Added style for the added HTML elements
- [x] Changed some styles from the previous branch

### Task C: JS

- [x] Added one route with delete method
- [x] Added one handler

  - Read the entire file
  - Check if there is a course with the given ID
  - Delete the course with the given ID
  - push the changes if these are valid to the file container(virtual copy of courses.json or the variable 'parsedData')
  - write the final changes to the database(courses.json)

- [x] Created two functions for displaying the form and fetching the data
- [x] Alert to user if it is done with success or failure

### Task D: fixing

- [x] fixing a bug(duplicate ID)
- [x] Changing the logging messages to better messages

---
