### ISSUE TITLE
Get-and-display

### ISSUE THREAD

**Issue by Sayed94h** [Sayed94h/Restful-API-WebApp#5]
## 2. Get-and-display the courses

> Assigned to _Sayed kazimi_

**As a user I want to be able to list all courses and also a specific course by its ID**

This part is create in a branch called `get-and-display` and merged in the `master` when it was completed.

### Task A: HTML

- [x] Added a form with two inputs, one for enter the course ID and another for to submit the input
- [x] Added many elements for rendering the data on website

### Task B: CSS

- [x] Added style for the added HTML elements

### Task C: JS

- [x] Added two routes
- [x] Added two handlers
- [x] Created two functions for fetching data

---
