### ISSUE TITLE
create-course

### ISSUE THREAD

**Issue by Sayed94h** [Sayed94h/Restful-API-WebApp#7]
## 3. create courses

> Assigned to _Sayed kazimi_

**As a user I want to be able to create course with a specific course name**

This part is create in a branch called `create-course` and merged in the `master` when it was completed.

### Task A: HTML

- [x] Added a form with two inputs, one for enter the course name and another for to submit the input

### Task B: CSS

- [x] Added style for the added HTML elements

### Task C: JS

- [x] Added one route
- [x] Added one handlers
  - Read the entire file
  - Validate the user input
  - push the user input if it is valid to the file content container
  - write the final changes to the database

- [x] Created two functions for creating the form and fetching the data
- [x] Alert to user if it is done with success or failure

---
