### ISSUE TITLE
update-course

### ISSUE THREAD

**Issue by Sayed94h** [Sayed94h/Restful-API-WebApp#9]
## 4. Edit or update courses

> Assigned to _Sayed kazimi_

**As a user I want to be able to edit the course name with a specific course id**

This part is create in a branch called `update-course` and merged in the `master` when it was completed.

### Task A: HTML

- [x] Added a form with three inputs, one for enter the course name, one for entering course ID and another for to submit the input
- [x] Added an h2 as a button for edit course

### Task B: CSS

- [x] Added style for the added HTML elements

### Task C: JS

- [x] Added one route with put method
- [x] Added one handlers

  - Read the entire file
  - Validate the user input
  - Change the course name with the new course name
  - push the changes if these are valid to the file content container
  - write the final changes to the database

- [x] Created two functions for displaying the form and fetching the data
- [x] Alert to user if it is done with success or failure

---
